### ISSUE TITLE
Pre-trained checkpoints

### ISSUE THREAD

**Issue by ozerodb** [vlb9ae/M-SpeechCLIP#1]
Hello, thank you very much for open-sourcing the code for M-SpeechCLIP, as I have been trying to replicate the paper's results starting from the original SpeechCLIP implementation. This will be an immense help in my research.

I wanted to ask: is there any plan to share the pre-trained checkpoints too? If not possible, I will train from scratch following the guidelines. To clarify, the checkpoint would be used for non-commercial, research purposes only.

Please let me know, and again thank you so much!🙏

**Comment by vlb9ae** [comment]
Yes, absolutely we plan on sharing the trained model weights! We'll need to discuss which trained models to publish and where to host them, so it'll likely be after ICASSP, but I'll be sure to have them up by the end of the month!

I'll leave this issue open until then as a reminder :)

**Comment by ozerodb** [comment]
I see, that's great news! Thank you so much again😁
